#ifndef MICROMACHINES_ENTITYTYPE_H
#define MICROMACHINES_ENTITYTYPE_H

#define TYPE_CAR 0
#define TYPE_WHEEL 15
#define TYPE_STATIC_OBJECT 10

/*---------TRACK_TILES---------*/
#define TYPE_SAND 63
#define TYPE_DIRT 28
#define TYPE_GRASS 59
#define TYPE_ASPHALT 27
#define TYPE_SPAWN_POINT 8

#define TYPE_FINISH_LINE_BORDER 9
#define TYPE_FINISH_LINE_CENTER 10

#define TYPE_F_PLACE_PODIUM 131
#define TYPE_S_PLACE_PODIUM 141
#define TYPE_T_PLACE_PODIUM 136
#define TYPE_NO_PODIUM_PLACE 36

/*---------MODIFIERS-----------*/
#define TYPE_BOOST 2145
#define TYPE_FIX 2146
#define TYPE_OIL 2147
#define TYPE_MUD 2148
#define TYPE_ROCK 2149

#endif //MICROMACHINES_ENTITYTYPE_