#ifndef MICROMACHINES_ENTITYTYPE_H
#define MICROMACHINES_ENTITYTYPE_H

#define TYPE_CAR 0
#define TYPE_STATIC_OBJECT 10
#define TYPE_WHEEL 15

/*---------TRACK_TILES---------*/
#define TYPE_GRASS 59
#define TYPE_ASPHALT 27
#define TYPE_SAND 63
#define TYPE_DIRT 28
#define TYPE_SPAWN_POINT 8

#define TYPE_FINISH_LINE_BORDER 9
#define TYPE_FINISH_LINE_CENTER 10

#endif //MICROMACHINES_ENTITYTYPE_H
