#ifndef MICROMACHINES_KEY_H
#define MICROMACHINES_KEY_H

#define ACCELERATE 11
#define BRAKE 12
#define TURN_LEFT 13
#define TURN_RIGHT 14

#define KEY_PRESSED 21
#define KEY_RELEASED 22

#endif //MICROMACHINES_KEY_H
