#ifndef MICROMACHINES_KEY_H
#define MICROMACHINES_KEY_H

#define KEY_UP 11
#define KEY_DOWN 12
#define KEY_LEFT 13
#define KEY_RIGHT 14
#define UNKNOWN_KEY 15

#define KEY_PRESSED 21
#define KEY_RELEASED 22


#endif //MICROMACHINES_KEY_H
