#ifndef MICROMACHINES_MSGTYPES_H
#define MICROMACHINES_MSGTYPES_H

#define NULL_UPDATE 100

#define MSG_UPDATE_ENTITY 41
#define MSG_SEND_TILE 42
#define MSG_CAR_ID 44
#define MSG_SET_HEALTH 45
#define MSG_SET_BACKGROUND 46
#define MSG_SET_LAP 47
#define MSG_TOTAL_LAPS 48
#define MSG_BEGIN_LOADING 49
#define MSG_FINISH_LOADING 50
#define MSG_COUNTDOWN 51
#define MSG_ADD_MODIFIER 52
#define MSG_REMOVE_MODIFIER 53
#define MSG_PLAYER_FINISHED 54

#define MSG_EFFECT_MUD 55
#define MSG_EFFECT_ROCK 56
#define MSG_EFFECT_BOOST 57

#endif //MICROMACHINES_MSGTYPES_H
