#ifndef MICROMACHINES_MSGTYPES_H
#define MICROMACHINES_MSGTYPES_H

#define MSG_UPDATE_ENTITY 41
#define MSG_SEND_TILE 42
#define MSG_TRACK_ID 43
#define MSG_CAR_ID 44
#define MSG_SET_HEALTH 45
#define MSG_SET_BACKGROUND 46

#endif //MICROMACHINES_MSGTYPES_H
