#ifndef MICROMACHINES_SIZES_H
#define MICROMACHINES_SIZES_H

#define TILE_TERRAIN_SIZE 2.5f
#define METER_TO_PIXEL 40.0f

#define CAR_WIDTH 2.0f
#define CAR_HEIGHT 4.0f

#define WIDTH_WHEEL 0.3f
#define HEIGHT_WHEEL 0.75f

#define HEIGHT_SCREEN 720
#define WIDTH_SCREEN 1024

#endif //MICROMACHINES_SIZES_H
