#ifndef MICROMACHINES_SIZES_H
#define MICROMACHINES_SIZES_H

#define METER_TO_PIXEL 40.0f

#define CAR_WIDTH 2.0f
#define CAR_HEIGHT 4.0f

#define WIDTH_WHEEL 0.2f
#define HEIGHT_WHEEL 0.65f

#define HEIGHT_SCREEN 600
#define WIDTH_SCREEN 800

#endif //MICROMACHINES_SIZES_H
